vm_configurations:
- bridge: PaloAlto1_vm1
  disk_size: 10G
  end_ip: 10.0.0.254
  memory: 2048
  password: root
  start_ip: 10.0.0.3
  subnet: 10.0.0.0/24
  username: root
  vcpus: 2
  vm_name: vm1
  vpc_id: PaloAlto1

