vm_configurations:
- bridge: tfa1-br1
  disk_size: 10G
  end_ip: 192.168.20.254
  hostname: r
  memory: 2048
  password: r
  psubnet: 100.10.0.0/30
  start_ip: 192.168.20.3
  subnet: 192.168.20.0/24
  username: r
  vcpus: 2
  veth_bridge: tfa1_br
  veth_namespace: tfa1_ns
  veth_provider: tfa1_pr
  veth_subnet: 100.64.0.0/30
  veth_vpc: tfa1_vpc
  vm_name: vm1
  vpc_id: tfa1
