vm_configurations:
- bridge: Arista1_vm1
  disk_size: 10G
  end_ip: 10.0.0.254
  memory: 2048
  password: root
  start_ip: 10.0.0.3
  subnet: 10.0.0.0/24
  username: root
  vcpus: 2
  veth_bridge: Arivm1_br
  veth_namespace: Arivm1_ns
  veth_subnet: 100.64.0.0/30
  vm_name: vm1
  vpc_id: Arista1
- bridge: Arista1_vm2
  disk_size: 20G
  end_ip: 10.0.1.254
  memory: 2048
  password: root
  start_ip: 10.0.1.3
  subnet: 10.0.1.0/24
  username: root
  vcpus: 2
  veth_bridge: Arivm2_br
  veth_namespace: Arivm2_ns
  veth_subnet: 100.64.0.0/30
  vm_name: vm2
  vpc_id: Arista1
- bridge: Arista2_vm3
  disk_size: 10G
  end_ip: 10.0.0.254
  memory: 2048
  password: root
  start_ip: 10.0.0.3
  subnet: 10.0.0.0/24
  username: root
  vcpus: 2
  veth_bridge: Arivm3_br
  veth_namespace: Arivm3_ns
  veth_subnet: 100.64.1.0/30
  vm_name: vm3
  vpc_id: Arista2
- bridge: Juniper1_vm4
  disk_size: 10G
  end_ip: 10.0.0.254
  memory: 2048
  password: root
  start_ip: 10.0.0.3
  subnet: 10.0.0.0/24
  username: root
  vcpus: 2
  veth_bridge: Junvm4_br
  veth_namespace: Junvm4_ns
  veth_subnet: 100.64.2.0/30
  vm_name: vm4
  vpc_id: Juniper1
