vm_configurations:
- bridge: PaloAlto1_VM9
  disk_size: 10G
  end_ip: 69.0.69.254
  memory: 2048
  password: root
  start_ip: 69.0.69.3
  subnet: 69.0.69.0/24
  username: root
  vcpus: 2
  veth_bridge: PalVM9_br
  veth_namespace: PalVM9_ns
  veth_subnet: 100.64.0.0/30
  vm_name: VM9
  vpc_id: PaloAlto1
- bridge: Arista1_VM1
  disk_size: 10G
  end_ip: 10.0.0.254
  memory: 2048
  password: ro
  start_ip: 10.0.0.3
  subnet: 10.0.0.0/24
  username: root
  vcpus: 2
  veth_bridge: AriVM1_br
  veth_namespace: AriVM1_ns
  veth_subnet: 100.64.1.0/30
  vm_name: VM1
  vpc_id: Arista1
- bridge: Arista1_VM2
  disk_size: 10G
  end_ip: 10.0.1.254
  memory: 2048
  password: root
  start_ip: 10.0.1.3
  subnet: 10.0.1.0/24
  username: root
  vcpus: 2
  veth_bridge: AriVM2_br
  veth_namespace: AriVM2_ns
  veth_subnet: 100.64.1.0/30
  vm_name: VM2
  vpc_id: Arista1
- bridge: Arista2_VM3
  disk_size: 10G
  end_ip: 10.0.0.254
  memory: 2048
  password: roo
  start_ip: 10.0.0.3
  subnet: 10.0.0.0/24
  username: roo
  vcpus: 2
  veth_bridge: AriVM3_br
  veth_namespace: AriVM3_ns
  veth_subnet: 100.64.2.0/30
  vm_name: VM3
  vpc_id: Arista2
- bridge: Arista2_VM4
  disk_size: 10G
  end_ip: 10.0.1.254
  memory: 2048
  password: root
  start_ip: 10.0.1.3
  subnet: 10.0.1.0/24
  username: root
  vcpus: 2
  veth_bridge: AriVM4_br
  veth_namespace: AriVM4_ns
  veth_subnet: 100.64.2.0/30
  vm_name: VM4
  vpc_id: Arista2
- bridge: Juniper1_VM1
  disk_size: 10G
  end_ip: 50.0.0.254
  memory: 2048
  password: root
  start_ip: 50.0.0.3
  subnet: 50.0.0.0/24
  username: root
  vcpus: 2
  veth_bridge: JunVM5_br
  veth_namespace: JunVM5_ns
  veth_subnet: 100.64.3.0/30
  vm_name: VM5
  vpc_id: Juniper1
- bridge: Juniper1_VM2
  disk_size: 10G
  end_ip: 50.0.10.254
  memory: 2048
  password: root
  start_ip: 50.0.10.3
  subnet: 50.0.10.0/24
  username: root
  vcpus: 2
  veth_bridge: JunVM6_br
  veth_namespace: JunVM6_ns
  veth_subnet: 100.64.3.0/30
  vm_name: VM6
  vpc_id: Juniper1
- bridge: Juniper2_VM3
  disk_size: 10G
  end_ip: 50.0.10.254
  memory: 2048
  password: root
  start_ip: 50.0.10.3
  subnet: 50.0.10.0/24
  username: root
  vcpus: 2
  veth_bridge: JunVM7_br
  veth_namespace: JunVM7_ns
  veth_subnet: 100.64.4.0/30
  vm_name: VM7
  vpc_id: Juniper2
- bridge: Juniper2_VM4
  disk_size: 10G
  end_ip: 50.0.20.254
  memory: 2048
  password: roo
  start_ip: 50.0.20.3
  subnet: 50.0.20.0/24
  username: roo
  vcpus: 2
  veth_bridge: JunVM8_br
  veth_namespace: JunVM8_ns
  veth_subnet: 100.64.4.0/30
  vm_name: VM8
  vpc_id: Juniper2
